### ISSUE TITLE
ისტორია გვჭირდება თუ არა, და შედოუზე მონაცემები ბაზაში შევინახოთ თუ RAM-ში?

### ISSUE THREAD

**Issue by wrinkl3** [freeuni-sdp/iot-bath-light-sensor#2]
@gkiko API-ს ნაწილად გვიწერია ისტორიის გამოტანის მეთოდები. გვჭირდება ეგენი, თუ შეგვიძლია წავშალოთ?
ასევე, თუ კი გვჭირდება, ბაზაში უნდა გვქონდეს შენახული თუ მეხსიერებაში?
თუკი ბაზაში, რომელი სერვისი გამოვიყენოთ მაგისთვის?

**Comment by gkiko** [comment]
შუქის სენსორს არ ჭირდება წარსული მონაცემები. შეგიძლია მხოლოდ უკანასკნელი
მდგომარეობა დაიმახსოვრო.

ბაზაში შენახვისთვის გვაქვს azure table storage. იხილე todo-core
On Jun 24, 2016 17:30, "wrinkl3" notifications@github.com wrote:

API-ს ნაწილად გვიწერია ისტორიის გამოტანის მეთოდები. გვჭირდება ეგენი, თუ
შეგვიძლია წავშალოთ?
ასევე, თუ კი გვჭირდება, ბაზაში უნდა გვქონდეს შენახული თუ მეხსიერებაში?
თუკი ბაზაში, რომელი სერვისი გამოვიყენოთ მაგისთვის?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/freeuni-sdp/iot-bath-light-sensor/issues/2, or mute
the thread
https://github.com/notifications/unsubscribe/ACdXhHQjuWDtKw3cOU97PPBAbk0eP1XKks5qO9vagaJpZM4I9xBx
.
